name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run full CI pipeline
        run: |
          npm run lint
          npm run typecheck
          npm test
          npm run build

      - name: Verify package can be packed
        run: npm pack --dry-run

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release Assets
        run: |
          npm pack
          mv *.tgz package.tgz

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./package.tgz
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tgz
          asset_content_type: application/gzip

      - name: Update Package Version Badge
        run: |
          echo "Package published successfully!"
          echo "Version: ${{ github.event.release.tag_name }}"
          echo "Package: @rumenx/sandbox-npm-package"